version: '3'
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 125M
    ports:
       - "1883:1883"
       - "9001:9001"
    volumes:
      - ./data-mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./data-mosquitto/data:/mosquitto/data
      - ./data-mosquitto/log:/mosquitto/log
  postgres:
    container_name: postgres
    image: postgres
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - ./data-postgres/:/var/lib/postgresql/data/
    deploy:
      resources:
        limits:
          memory: 250M